### ISSUE TITLE
Endless bot replies on messenger

### ISSUE THREAD

**Issue by Piyushhbhutoria** [SAPConversationalAI/SAPConversationalAI#102]
I integrated simple greeting bot on my facebook page i typed in hello.
It is now endlessly replying to my hello, i tried replying bye but, it it still replying to my hi endlessly.

I tried on telegram also but, still facing the same issue.
how is it happening?

**Comment by aurelie-lamy** [comment]
Hi @Piyushhbhutoria 

Do you still have your issue?

Aurélie

**Comment by Piyushhbhutoria** [comment]
yes

**Comment by aurelie-lamy** [comment]
can you try to add an expression on one intent to train your bot again?

**Comment by Piyushhbhutoria** [comment]
Thank you, its fixed.
