### ISSUE TITLE
Can't copy Basic authentications when versioning

### ISSUE THREAD

**Issue by SofiaPe** [SAPConversationalAI/SAPConversationalAI#109]
Hi,
I am working on a Bot with a couple of versions, but everytime I create a new one I have to manually add and create a new authentication template, it does not copy the original to the new version. Is there any way this can get done automatically?

It should look like this: 
![a](https://user-images.githubusercontent.com/44376168/48557802-b51b7400-e8b5-11e8-97bf-9438b0a89cb3.PNG)
![b](https://user-images.githubusercontent.com/44376168/48557807-b8aefb00-e8b5-11e8-95d0-9186e78012c0.PNG)

instead it looks like this:
![c](https://user-images.githubusercontent.com/44376168/48557818-c3699000-e8b5-11e8-896a-0b9213d597f8.PNG)
![d](https://user-images.githubusercontent.com/44376168/48557817-c3699000-e8b5-11e8-8c37-8d96ddbc5240.PNG)

It's also not alowing me to create the authentication on the already existing block of requirement, but I have to create it from start and if I want to change the logic on the skill I also have to recreate every block, can't just drag them on an specific order.

Thanks for the help!

**Comment by yimialejoh** [comment]
It's the same with me, is there a solution for it?

**Comment by aurelie-lamy** [comment]
bug card created (SAPLMCONV-1198)

**Comment by aurelie-lamy** [comment]
Hi @SofiaPe 

 After internal discussions, it is not a bug, it was a security-related decision not to copy authentication when we developed Versioning.

Regards,

Aurélie
