### ISSUE TITLE
Quick Reply Buttons  problem --> TELEGRAM messenger

### ISSUE THREAD

**Issue by genshtab** [SAPConversationalAI/SAPConversationalAI#120]
Hello there, 
After  testing thу bot within Recast debug chat,  I`ve connected it into the Telegram platform. 
**Issue:** 
-  QuickReplies buttons  do not send their  values to Telegram chat. If it helps - values are -> NUMBERS. 

note: There is  no such problem when bot sends the same data into Recast test  chat.

**Comment by aurelie-lamy** [comment]
(card created : SAPMLCONV-1032)

**Comment by aurelie-lamy** [comment]
HI @genshtab 

we are working on this issue, it will be fixed by the end of January :)

best,

**Comment by aurelie-lamy** [comment]
Hi @genshtab 

it is fixed :)

Regards,
