### ISSUE TITLE
after creating a list response and deleting an item, items below the next item can't set title, subtitle etc

### ISSUE THREAD

**Issue by tiulimg** [SAPConversationalAI/SAPConversationalAI#125]
instead, the next item itself is being edited and not the items below it, and only one letter is allowed in title/subtitle..

**Comment by aurelie-lamy** [comment]
Hi @tiulimg 

do you still have this issue?
If yes, can you provide us the steps to reproduce and screenshot please?

Many thanks :)

**Comment by tiulimg** [comment]
still happens
https://www.dropbox.com/s/09hgutisaoszc1b/Untitled.avi?dl=0

create a new list with 2 or 3 items,
save it,
edit it and remove upper or median items,
add a new item and try to edit it. it will edit the previous item instead and will allow you to insert only 1 letter.

**Comment by aurelie-lamy** [comment]
Hi @tiulimg 

thanks for your reply. I created a card to fix it (SAPMLCONV-1344).
I let you know when it will be fixed

Aurélie

**Comment by aurelie-lamy** [comment]
Hey @tiulimg 

the issue has been fixed!

Aurélie
