### ISSUE TITLE
Alexa integration with Recast.AI bot is not working

### ISSUE THREAD

**Issue by ashwani-luhaniwal** [SAPConversationalAI/SAPConversationalAI#129]
Currently, I am trying to integrate our Recast bot with Alexa bot. I have followed all the steps which were listed by Recast in the channel guidelines. After successful deployment to Alexa, when I call our bot from Alexa then we are getting the following error.  The Alexa chat response was **There is a problem with the requested skills response**

Here I have attached the Input JSON along with Output JSON which we are getting in Alexa logs. Could you please help me here as I am not able to figure out what's happening. It seems from Alexa call is happening successfully in the Recast as I am able to see intent calls in Monitor section where as somehow the response is not going to Alexa bot.

**Input JSON**

` ` ` json
{
  "version": "1.0",
  "session": {
    "new": true,
    "sessionId": "amzn1.echo-api.session.2765a204-9ab6-4a1a-b32c-c22e92831d08",
    "application": {
      "applicationId": "amzn1.ask.skill.39cb5bbd-a817-4b98-95fb-b9366db21973"
    },
    "user": {
      "userId": "amzn1.ask.account.AFDRQWXDQCA7IYJONBAQV7SX74GDOLHNNZGNL5S6NU4CBWLMIWSEBSGP6XYOFUWQE6A3TD4FNCTJ7UMVQ4ZXJ3XAF37CP5KPJYOVS6WHVZUTQPFEDYMLHGYBKOLWGTWD3FB46CSIBAZVBELG7UGXO7GIK2AEKCO3T5QTNGPQJNIIJWJTNJXOJPURGADEJKMAC32NOUA7VB2RGFQ"
    }
  },
  "context": {
    "System": {
      "application": {
        "applicationId": "amzn1.ask.skill.39cb5bbd-a817-4b98-95fb-b9366db21973"
      },
      "user": {
        "userId": "amzn1.ask.account.AFDRQWXDQCA7IYJONBAQV7SX74GDOLHNNZGNL5S6NU4CBWLMIWSEBSGP6XYOFUWQE6A3TD4FNCTJ7UMVQ4ZXJ3XAF37CP5KPJYOVS6WHVZUTQPFEDYMLHGYBKOLWGTWD3FB46CSIBAZVBELG7UGXO7GIK2AEKCO3T5QTNGPQJNIIJWJTNJXOJPURGADEJKMAC32NOUA7VB2RGFQ"
      },
      "device": {
        "deviceId": "amzn1.ask.device.AGP3BT7TNJEFFUHD7VZ724UB3RNYPDA22EAWVEVWFPIEUJ2YEEI57QGGB62XEFXAB34UYDQNCNXZ6QSBFGGILUTCD45ZWE54Y7CV5Q76PY7WNRT74FW6JMBFGTVB5GPHJUOAIODOCZVB3HTE3YBYPYUEXR6QMRYFRMUCQNL5SDM6W55E5QS7K",
        "supportedInterfaces": {}
      },
      "apiEndpoint": "https://api.eu.amazonalexa.com",
      "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjM5Y2I1YmJkLWE4MTctNGI5OC05NWZiLWI5MzY2ZGIyMTk3MyIsImV4cCI6MTU0NjQzMTY1MCwiaWF0IjoxNTQ2NDI4MDUwLCJuYmYiOjE1NDY0MjgwNTAsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUdQM0JUN1ROSkVGRlVIRDdWWjcyNFVCM1JOWVBEQTIyRUFXVkVWV0ZQSUVVSjJZRUVJNTdRR0dCNjJYRUZYQUIzNFVZRFFOQ05YWjZRU0JGR0dJTFVUQ0Q0NVpXRTU0WTdDVjVRNzZQWTdXTlJUNzRGVzZKTUJGR1RWQjVHUEhKVU9BSU9ET0NaVkIzSFRFM1lCWVBZVUVYUjZRTVJZRlJNVUNRTkw1U0RNNlc1NUU1UVM3SyIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFGRFJRV1hEUUNBN0lZSk9OQkFRVjdTWDc0R0RPTEhOTlpHTkw1UzZOVTRDQldMTUlXU0VCU0dQNlhZT0ZVV1FFNkEzVEQ0Rk5DVEo3VU1WUTRaWEozWEFGMzdDUDVLUEpZT1ZTNldIVlpVVFFQRkVEWU1MSEdZQktPTFdHVFdEM0ZCNDZDU0lCQVpWQkVMRzdVR1hPN0dJSzJBRUtDTzNUNVFUTkdQUUpOSUlKV0pUTkpYT0pQVVJHQURFSktNQUMzMk5PVUE3VkIyUkdGUSJ9fQ.BFSDEo3zUKInczRn8bEvz0J9GT5C1AXdWzsBKh-wM1nbdesZuUM4mStIgu6FnxqInBGH77ElHyq0P740PpeiD1sXajJpB0rNdJLef1aJT1-f1Zjf88qCSywcU67gQitn7lcjn9oQjS7pCL7eauKKpB9UKdHxvjlgkUWLMKNViS7OBJZOJU_7bTeA0Dd0w3rhY2ojL1Qmu1Gty6kescLi4kbK2HfqHYbUOwkXTi0ic-ZAUF3ti9KcwqkFFtvIv138QlW_2ge-99FfVnCGkwnCLq0HacSdONr75KdnSzzzBdg7yYr23lKxSB7tQF7XDvIkjuwGR2pwMo8jLNGkJBaTgg"
    },
    "Viewport": {
      "experiences": [
        {
          "arcMinuteWidth": 246,
          "arcMinuteHeight": 144,
          "canRotate": false,
          "canResize": false
        }
      ],
      "shape": "RECTANGLE",
      "pixelWidth": 1024,
      "pixelHeight": 600,
      "dpi": 160,
      "currentPixelWidth": 1024,
      "currentPixelHeight": 600,
      "touch": [
        "SINGLE"
      ]
    }
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "amzn1.echo-api.request.05b255dc-0d64-4b03-8a49-959551bc498b",
    "timestamp": "2019-01-02T11:20:50Z",
    "locale": "en-IN",
    "intent": {
      "name": "CATCH_ALL_INTENT",
      "confirmationStatus": "NONE",
      "slots": {
        "CATCH_ALL_SLOT": {
          "name": "CATCH_ALL_SLOT",
          "value": "orders",
          "resolutions": {
            "resolutionsPerAuthority": [
              {
                "authority": "amzn1.er-authority.echo-sdk.amzn1.ask.skill.39cb5bbd-a817-4b98-95fb-b9366db21973.CATCH_ALL_SLOT_TYPE",
                "status": {
                  "code": "ER_SUCCESS_NO_MATCH"
                }
              }
            ]
          },
          "confirmationStatus": "NONE",
          "source": "USER"
        }
      }
    }
  }
}
` ` `

**Output JSON**

` ` ` json 
{
  "body": {
    "version": "1.0",
    "response": {},
    "sessionAttributes": {},
    "userAgent": "ask-node/2.0.7 Node/v8.12.0"
  }
}
` ` `

Even when I try to call the recast api webhook url in the browser then we are getting errors something like **service is not implemented**

**Comment by aurelie-lamy** [comment]
SAPMLCONV-1204

**Comment by ashwani-luhaniwal** [comment]
Hi Aurelie,

Could you specify what is the meaning of SAPMLCONV-1204 as I am not able to understand it.

**Comment by aurelie-lamy** [comment]
Hi Ashwani,

Sorry l, it is only the card number of your issue. I will update you when I have more information 

Regards

Aurélie

**Comment by gaurav-sahay** [comment]
@ashwani-luhaniwal : Were you able to resolve the issue?
@aurelie-lamy : Even i am facing the same issue. Can you please provide some update or info or workaround to resolve the issue. Thanks in advance

**Comment by D161764** [comment]
hi is that issue resolved because i am also facing the same issue

**Comment by D161764** [comment]
this issue is solved, i am able to connect alexa.

**Comment by ashwani-luhaniwal** [comment]
> hi is that issue resolved because i am also facing the same issue

I am facing the same issue, not able to connect to Alexa also.

**Comment by D161764** [comment]
hi aswani, this issue is resolved make sure you have redirected ur alexa trigger skill to any of the welcome or greet skill which u have created.

**Comment by ashwani-luhaniwal** [comment]
Yeah, now the integration of Alexa with Recast is working perfectly for me. 👍 Thanks for sharing your inputs here. :)
