### ISSUE TITLE
Unable to upload enitity gazette csv file

### ISSUE THREAD

**Issue by pascaljung** [SAPConversationalAI/SAPConversationalAI#72]
Hi,

when I try to upload a csv file to define an entity gazette, I get the following error:
![image](https://user-images.githubusercontent.com/4255969/44915725-02b32680-ad34-11e8-9a44-6849839b57a5.png)

This problem only occurs on Windows machines, since Windows seems to detect the csv file as "application/vnd.ms-excel" mime type instead of "text/csv".

Thanks and best regards,
Pascal

**Comment by janteuni** [comment]
Nice :)
@indispira Is investigating to fix it  as soon as possible :)

**Comment by aurelie-lamy** [comment]
Hi, it will be fixed by the end of december.

**Comment by aurelie-lamy** [comment]
Hi @pascaljung 

We're running behind, this issue will be fixed by the end of january .. our team is currently working on it

best

**Comment by pascaljung** [comment]
Hi @aurelie-lamy,

thanks for the fix. Unfortunately, I'm now not able to open the entity page at all. After a few seconds, the window turns white (like a blank HTML page). I already tried to clear the cache, however, that didn't help. I use Chrome in Version 71.0.3578.98

The console shows the following output:
![image](https://user-images.githubusercontent.com/4255969/51846680-5a24e500-231a-11e9-8a61-30b44d439235.png)

Best regards,
Pascal

**Comment by aurelie-lamy** [comment]
Hi @pascaljung 

do you still have your issue?
if yes, could you add me as member of your bot please (aurelie-nesty).
thanks,

Aurélie

**Comment by aurelie-lamy** [comment]
Hi @pascaljung 

Could you try again to upload your file?
On my side, everything works well, I hope in your side too :)

Let me know if is works or not!

Many thanks,

Aurélie

**Comment by pascaljung** [comment]
Hi @aurelie-lamy,

sorry for the late response. I just tested it again, works now as intended! I close the issue.

Thanks and best regards,
Pascal
