### ISSUE TITLE
How to pass user ID while initiating a session and retrieve old chat when same ID is passed again 

### ISSUE THREAD

**Issue by WhitedeathHarry** [SAPConversationalAI/SAPConversationalAI#97]
Hi All,

I need support urgently on passing user ID while starting a chat. As in my usecase i already know who my user is so i don't want to ask username or ID. Also when user return i want to show him all the old chat. Please help.

**Comment by boudhayan-dev** [comment]
Any progress @WhitedeathHarry  ?

**Comment by dbousque** [comment]
Hi @boudhayan-dev, if you're using the webchat, take a look at the "Bot memory management" part here : https://cai.tools.sap/docs/concepts/webchat

**Comment by Vinay0291** [comment]
Is it only possible via WebChat ? Can't it be handled at Conversational AI level ?
